### ISSUE TITLE
没更新了呀

### ISSUE THREAD

**Issue by JimTomY** [shaojs/tampermonkey#1]
老哥离职了么，脚本没更新了呀；；修改以下可用

`// ==UserScript==
// @name         浪潮大学自动刷视频 M—Learning
// @namespace    cn.shaojs.tampermonkey.mlearning
// @version      1.0.3
// @description  浪潮大学视频播放 文档浏览
// @author       shaojs
// @icon         https://picobd.yunxuetang.cn/sys/18653182312/images/202009/05d332081dbc4370b1dd7b184def21de.ico
// @match        http://edu.inspur.com/plan/*.html
// @match        http://edu.inspur.com/kng/plan/document/*
// @match        http://edu.inspur.com/kng/view/document/*
// @match        http://edu.inspur.com/kng/plan/video/*
// @match        http://edu.inspur.com/kng/view/video/*
// @match        http://edu.inspur.com/kng/view/package/*
// @match        http://edu.inspur.com/kng/plan/package/*
// @match        http://edu.inspur.com/mit/myhomeworkexprience*
// @match        http://edu.inspur.com/kng/course/package/video/*
// @match        http://edu.inspur.com/kng/course/package/document/*
// @match        http://edu.inspur.com/sty/index.htm
// @match        https://edu.inspur.com/kng/plan/package/*
// @grant        GM_xmlhttpRequest
// @grant        unsafeWindow
// @connect      https://github.com/shaojs/tampermonkey
// @require      https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js
// ==/UserScript==

(function () {
    const path = window.location.pathname;
    const date = new Date();

    var host = "http://edu.inspur.com" + window.location.host;

    var short_scan_seconds = 5;
    var long_scan_seconds = 10;`

**Comment by shaojs** [comment]
感谢提醒，好久没刷课了。网站改https了
